# Generated by Django 3.0.8 on 2020-09-07 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200906_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
