# Generated by Django 3.0.8 on 2020-08-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200822_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shortUsername',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 12 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=12, unique=True),
        ),
    ]
